/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package provisionamento.view;

import Sistema.ConcreteSubject;
import Sistema.Observer;
import Sistema.Session;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import provisionamento.controller.FramePrincipalController;
import provisionamento.model.GrupoComunitario;
import provisionamento.model.GrupoUnitario;
import provisionamento.model.Mensagem;

/**
 *
 * @author Lucas
 */
public class FramePrincipal extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form FramePrincipal
     */
    FramePrincipalController controller;

    public FramePrincipal() {
        try {
            initComponents();
            controller = new FramePrincipalController();

            List<Mensagem> mensagens = Session.getInstancia().getUsuarioLogado().getMensagens();
            for (Mensagem mensagem : mensagens) {
                listaMensagens.addElement(mensagem);
            }
            
            lsNotificacoes.setModel(listaMensagens);

            lbUsuLogado.setText(lbUsuLogado.getText() + Session.getInstancia().getUsuarioLogado().getNome() + "!");

            ArrayList<GrupoComunitario> grupoParticipante =
                    controller.getGruposParticipante(
                    Session.getInstancia().getUsuarioLogado());

            ArrayList<GrupoComunitario> grupoCriador =
                    controller.getGruposCriador(
                    Session.getInstancia().getUsuarioLogado());

            ArrayList<GrupoUnitario> grupoPessoal =
                    controller.getGruposPessoais(
                    Session.getInstancia().getUsuarioLogado());

            DefaultListModel<GrupoComunitario> modelSeusGrupos =
                    new DefaultListModel<>();

            DefaultListModel<GrupoUnitario> modelGruposPessoais =
                    new DefaultListModel<>();

            DefaultListModel<GrupoComunitario> modelGruposParticipantes =
                    new DefaultListModel<>();

            lsSeusGrupos.setModel(modelSeusGrupos);
            lsGruposPessoais.setModel(modelGruposPessoais);
            lsGruposComunParticipa.setModel(modelGruposParticipantes);

            for (GrupoComunitario grupoComunitario : grupoCriador) {
                modelSeusGrupos.addElement(grupoComunitario);
            }

            for (GrupoUnitario grupoUnitario : grupoPessoal) {
                modelGruposPessoais.addElement(grupoUnitario);
            }

            for (GrupoComunitario grupoComunitario : grupoParticipante) {
                modelGruposParticipantes.addElement(grupoComunitario);
            }

            ConcreteSubject.getInstancia().registerObserver(this);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    private FrameGrupoUnitario frameGrupo;
    private FrameGrupoComunitario frameGrupoComunitario;
    private DefaultListModel<Mensagem> listaMensagens = new DefaultListModel<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lbUsuLogado = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btGrupo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsSeusGrupos = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsGruposComunParticipa = new javax.swing.JList();
        btGrupoComunitario = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        BtAddUsuario = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lsGruposPessoais = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lsNotificacoes = new javax.swing.JList();
        btAtender = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Provisionamento");

        jLabel2.setText("Suas Notificacões");

        lbUsuLogado.setText("Bom vê-lo novamente por aqui, ");

        btGrupo.setText("Adicionar Novo Grupo");
        btGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrupoActionPerformed(evt);
            }
        });

        jLabel4.setText("Seus Grupos Comunitários");

        lsSeusGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsSeusGruposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lsSeusGrupos);

        jLabel5.setText("Grupos em que você está");

        jScrollPane3.setViewportView(lsGruposComunParticipa);

        btGrupoComunitario.setText("Adicionar Novo Grupo Comunitário");
        btGrupoComunitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrupoComunitarioActionPerformed(evt);
            }
        });

        btLogout.setText("Logout");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        jLabel3.setText("Relatórios");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Relatórios das Minha Dívidas");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Relatórios de Meus Devedores");

        jButton1.setText("Gerar");

        BtAddUsuario.setText("Cadastrar Usuario");
        BtAddUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddUsuarioActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(lsGruposPessoais);

        jLabel6.setText("Grupos pessoais");

        lsNotificacoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(lsNotificacoes);

        btAtender.setText("Atender");
        btAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtenderActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60)
                                .addComponent(btLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtAddUsuario)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(346, 346, 346))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbUsuLogado)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(btGrupoComunitario, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(502, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAtender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtAddUsuario)
                            .addComponent(btLogout))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUsuLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAtender)
                        .addGap(16, 16, 16)
                        .addComponent(btRemover)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGrupoComunitario)
                    .addComponent(btGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrupoActionPerformed
        frameGrupo = new FrameGrupoUnitario();
        frameGrupo.setVisible(true);
    }//GEN-LAST:event_btGrupoActionPerformed

    private void btGrupoComunitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrupoComunitarioActionPerformed
        frameGrupoComunitario = new FrameGrupoComunitario();
        frameGrupoComunitario.setVisible(true);
    }//GEN-LAST:event_btGrupoComunitarioActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        Session.getInstancia().setUsuarioLogado(null);
        new FrameLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLogoutActionPerformed

    private void BtAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddUsuarioActionPerformed
        new FrameUsuario().setVisible(true);
    }//GEN-LAST:event_BtAddUsuarioActionPerformed

    private void lsSeusGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsSeusGruposMouseClicked
        GrupoComunitario com = (GrupoComunitario) lsSeusGrupos.getSelectedValue();
        new FrameGrupoComunitarioSituacao(com).setVisible(true);
    }//GEN-LAST:event_lsSeusGruposMouseClicked

    private void btAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtenderActionPerformed
        Mensagem mensagem = (Mensagem) lsNotificacoes.getSelectedValue();
        if(mensagem.getGrupo() instanceof GrupoComunitario){
            frameGrupoComunitario = new FrameGrupoComunitario((GrupoComunitario) mensagem.getGrupo());
            frameGrupoComunitario.setVisible(true);
        } else{
            frameGrupo = new FrameGrupoUnitario(mensagem.getGrupo());
            frameGrupo.setVisible(true);
        }
        mensagem.getGrupo().setFinalizado(true);
        listaMensagens.removeElement(mensagem);
    }//GEN-LAST:event_btAtenderActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        Mensagem mensagem = (Mensagem) lsNotificacoes.getSelectedValue();
        mensagem.getGrupo().setFinalizado(true);
    }//GEN-LAST:event_btRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAddUsuario;
    private javax.swing.JButton btAtender;
    private javax.swing.JButton btGrupo;
    private javax.swing.JButton btGrupoComunitario;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btRemover;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbUsuLogado;
    private javax.swing.JList lsGruposComunParticipa;
    private javax.swing.JList lsGruposPessoais;
    private javax.swing.JList lsNotificacoes;
    private javax.swing.JList lsSeusGrupos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Object obj) {
        if (obj instanceof GrupoComunitario) {

            GrupoComunitario grupo = (GrupoComunitario) obj;
            if (grupo.getCriador().equals(Session.getInstancia().getUsuarioLogado())) {
                DefaultListModel<GrupoComunitario> modelSeusGrupos =
                        (DefaultListModel<GrupoComunitario>) lsSeusGrupos.getModel();
                modelSeusGrupos.addElement(grupo);
            } else {
                DefaultListModel<GrupoComunitario> modelGruposParticipantes =
                        (DefaultListModel<GrupoComunitario>) lsGruposComunParticipa.getModel();
                modelGruposParticipantes.addElement(grupo);
            }

        } else if (obj instanceof GrupoUnitario) {

            DefaultListModel<GrupoUnitario> modelGruposPessoais =
                    (DefaultListModel<GrupoUnitario>) lsGruposPessoais.getModel();

            GrupoUnitario grupoUnitario = (GrupoUnitario) obj;
            if (grupoUnitario.getCriador().equals(Session.getInstancia().getUsuarioLogado())) {
                modelGruposPessoais.addElement(grupoUnitario);
            }
        }
    }
}
